export const FAKE_POPULARS = [
  {
    backdrop_path: "/t2rAdgjSh0WYbXzdOB5zTDqzdCI.jpg",
    first_air_date: "2022-11-02",
    genre_ids: [18],
    id: 213713,
    name: "Faltu",
    origin_country: ["IN"],
    original_language: "hi",
    original_name: "Faltu",
    overview:
      "What's in a name? Amidst the arid landscape of Rajasthan, a young woman with dreamy eyes struggles to prove her worth.",
    popularity: 2139.457,
    poster_path: "/lgyFuoXs7GvKJN0mNm7z7OMOFuZ.jpg",
    vote_average: 4.3,
    vote_count: 21,
  },
];

export const FAKE_RECOMMENDATIONS = [
  {
    adult: false,
    backdrop_path: "/3Yg9TURGv1WUlFIGOhDMLM6mOHY.jpg",
    id: 218886,
    name: "Al Aghar",
    original_language: "ar",
    original_name: "الأجهر",
    overview:
      "Falsely accused of killing his mom, a teen continues his life abroad on the run. But his return home to find his family uncovers mysterious secrets about his past.",
    poster_path: "/4SqZASKpIG28TSYvopLedhBDIn3.jpg",
    media_type: "tv",
    genre_ids: [18],
    popularity: 7.582,
    first_air_date: "2023-03-23",
    vote_average: 6.5,
    vote_count: 4,
    origin_country: ["EG"],
  },
  {
    adult: false,
    backdrop_path: "/zEj8eKk2Z3OG8zo9IjpHXSjKA3Y.jpg",
    id: 203763,
    name: "Udan Patolas",
    original_language: "hi",
    original_name: "Udan Patolas",
    overview:
      "4 small town girls try to hilariously fit in the big city. They maybe unlucky in love but their sisterhood is unbreakable.",
    poster_path: "/pB090Pg2RKr6g59FNEIp6zc7mZ7.jpg",
    media_type: "tv",
    genre_ids: [18],
    popularity: 2.454,
    first_air_date: "2022-06-10",
    vote_average: 8.5,
    vote_count: 2,
    origin_country: ["IN"],
  },
  {
    adult: false,
    backdrop_path: "/uDgy6hyPd82kOHh6I95FLtLnj6p.jpg",
    id: 100088,
    name: "The Last of Us",
    original_language: "en",
    original_name: "The Last of Us",
    overview:
      "Twenty years after modern civilization has been destroyed, Joel, a hardened survivor, is hired to smuggle Ellie, a 14-year-old girl, out of an oppressive quarantine zone. What starts as a small job soon becomes a brutal, heartbreaking journey, as they both must traverse the United States and depend on each other for survival.",
    poster_path: "/uKvVjHNqB5VmOrdxqAt2F7J78ED.jpg",
    media_type: "tv",
    genre_ids: [18],
    popularity: 548.95,
    first_air_date: "2023-01-15",
    vote_average: 8.743,
    vote_count: 3399,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/caGVr9Il2gj8bN4ow6qsLm60TxM.jpg",
    id: 1416,
    name: "Grey's Anatomy",
    original_language: "en",
    original_name: "Grey's Anatomy",
    overview:
      "Follows the personal and professional lives of a group of doctors at Seattle’s Grey Sloan Memorial Hospital.",
    poster_path: "/daSFbrt8QCXV2hSwB0hqYjbj681.jpg",
    media_type: "tv",
    genre_ids: [18],
    popularity: 495.143,
    first_air_date: "2005-03-27",
    vote_average: 8.258,
    vote_count: 9154,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/azWBrlovNOOdy0eQYEe9BoiROoN.jpg",
    id: 209085,
    name: "Amor Perfeito",
    original_language: "pt",
    original_name: "Amor Perfeito",
    overview: "",
    poster_path: "/aOPhyvHDauWFuc3rthpHArCNyrm.jpg",
    media_type: "tv",
    genre_ids: [18, 10766],
    popularity: 20.157,
    first_air_date: "2023-03-20",
    vote_average: 4.8,
    vote_count: 5,
    origin_country: ["BR"],
  },
  {
    adult: false,
    backdrop_path: "/zrMCOQnzIgGyBtGCdMPom9bOw0r.jpg",
    id: 62286,
    name: "Fear the Walking Dead",
    original_language: "en",
    original_name: "Fear the Walking Dead",
    overview:
      'What did the world look like as it was transforming into the horrifying apocalypse depicted in "The Walking Dead"? This spin-off set in Los Angeles, following new characters as they face the beginning of the end of the world, will answer that question.',
    poster_path: "/zyshFjmlDXSzfns2Qk81cfIFfPP.jpg",
    media_type: "tv",
    genre_ids: [10759, 18],
    popularity: 147.987,
    first_air_date: "2015-08-23",
    vote_average: 7.692,
    vote_count: 4444,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/mt3SRKq7uRBKVntaBg2ofsDfOdg.jpg",
    id: 4629,
    name: "Stargate SG-1",
    original_language: "en",
    original_name: "Stargate SG-1",
    overview:
      "The story of Stargate SG-1 begins about a year after the events of the feature film, when the United States government learns that an ancient alien device called the Stargate can access a network of such devices on a multitude of planets. SG-1 is an elite Air Force special operations team, one of more than two dozen teams from Earth who explore the galaxy and defend against alien threats such as the Goa'uld, Replicators, and the Ori.",
    poster_path: "/rst5xc4f7v1KiDiQjzDiZqLtBpl.jpg",
    media_type: "tv",
    genre_ids: [10765, 10759, 9648],
    popularity: 157.954,
    first_air_date: "1997-07-27",
    vote_average: 8.256,
    vote_count: 1293,
    origin_country: ["CA", "US"],
  },
  {
    adult: false,
    backdrop_path: "/he4mtQe9KWsXpScDf3seER8Pkq6.jpg",
    id: 105248,
    name: "Cyberpunk: Edgerunners",
    original_language: "ja",
    original_name: "サイバーパンク：エッジランナーズ",
    overview:
      "In a dystopia riddled with corruption and cybernetic implants, a talented but reckless street kid strives to become a mercenary outlaw — an edgerunner.",
    poster_path: "/7jSWOc6jWSw5hZ78HB8Hw3pJxuk.jpg",
    media_type: "tv",
    genre_ids: [10759, 16, 10765],
    popularity: 50.21,
    first_air_date: "2022-09-13",
    vote_average: 8.611,
    vote_count: 862,
    origin_country: ["JP"],
  },
  {
    adult: false,
    backdrop_path: "/cEcjyE8UwVdnneTmbqDvRhlY6Np.jpg",
    id: 213044,
    name: "LUPIN ZERO",
    original_language: "ja",
    original_name: "LUPIN ZERO",
    overview:
      "The childhood adventures of Arsène Lupin III, set in the early 1960s before he achieved global infamy.",
    poster_path: "/zbUyE5Lc70yi88LHalRM7KFj89a.jpg",
    media_type: "tv",
    genre_ids: [16, 9648, 80, 10759],
    popularity: 9.421,
    first_air_date: "2022-12-16",
    vote_average: 7.9,
    vote_count: 7,
    origin_country: ["JP"],
  },
  {
    adult: false,
    backdrop_path: "/nWfpVLgioDXQsAbfL6UJxYz6d3d.jpg",
    id: 16997,
    name: "The Pacific",
    original_language: "en",
    original_name: "The Pacific",
    overview:
      "Track the intertwined real-life stories of three U.S. Marines – Robert Leckie, John Basilone, and Eugene Sledge – across the vast canvas of the Pacific Theater during World War II. A companion piece to the 2001 miniseries Band of Brothers.",
    poster_path: "/x9Y1IMFdY8Ma222KcQadFEau0EB.jpg",
    media_type: "tv",
    genre_ids: [18, 10759, 10768],
    popularity: 35.548,
    first_air_date: "2010-03-14",
    vote_average: 7.73,
    vote_count: 2062,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/4u64tHtUkna1y4OkJcrXLEhhLLy.jpg",
    id: 110070,
    name: "Horimiya",
    original_language: "ja",
    original_name: "ホリミヤ",
    overview:
      "A secret life is the one thing they have in common. At school, Hori is a prim and perfect social butterfly, but the truth is she's a brash homebody. Meanwhile, under a gloomy facade, Miyamura hides a gentle heart, along with piercings and tattoos. In a chance meeting, they both reveal a side they've never shown. Could this blossom into something new?",
    poster_path: "/917VL7zHTaltnEBDrKWVITTsvLy.jpg",
    media_type: "tv",
    genre_ids: [16, 35, 18],
    popularity: 44.146,
    first_air_date: "2021-01-10",
    vote_average: 8.6,
    vote_count: 737,
    origin_country: ["JP"],
  },
  {
    adult: false,
    backdrop_path: "/99vBORZixICa32Pwdwj0lWcr8K.jpg",
    id: 130392,
    name: "The D'Amelio Show",
    original_language: "en",
    original_name: "The D'Amelio Show",
    overview:
      "From relative obscurity and a seemingly normal life, to overnight success and thrust into the Hollywood limelight overnight, the D’Amelios are faced with new challenges and opportunities they could not have imagined.",
    poster_path: "/phv2Jc4H8cvRzvTKb9X1uKMboTu.jpg",
    media_type: "tv",
    genre_ids: [10764],
    popularity: 7.457,
    first_air_date: "2021-09-03",
    vote_average: 4.892,
    vote_count: 662,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/hKxGRAPFHEjNWNLM6yl2WoiXJiJ.jpg",
    id: 31109,
    name: "Ben 10: Ultimate Alien",
    original_language: "en",
    original_name: "Ben 10: Ultimate Alien",
    overview:
      "With his secret identity now revealed to the world, Ben Tennyson continues to fight evil as a superhero with the help of the newly acquired Ultimatrix.",
    poster_path: "/n4KwrlUKO9S4GvOdZzmnz4zOxx7.jpg",
    media_type: "tv",
    genre_ids: [16, 10759, 10765],
    popularity: 52.208,
    first_air_date: "2010-04-23",
    vote_average: 8.187,
    vote_count: 709,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/vXpeJJs1z8OKC88CNJX9O9QOhtr.jpg",
    id: 94997,
    name: "House of the Dragon",
    original_language: "en",
    original_name: "House of the Dragon",
    overview:
      "The Targaryen dynasty is at the absolute apex of its power, with more than 15 dragons under their yoke. Most empires crumble from such heights. In the case of the Targaryens, their slow fall begins when King Viserys breaks with a century of tradition by naming his daughter Rhaenyra heir to the Iron Throne. But when Viserys later fathers a son, the court is shocked when Rhaenyra retains her status as his heir, and seeds of division sow friction across the realm.",
    poster_path: "/1X4h40fcB4WWUmIBK0auT4zRBAV.jpg",
    media_type: "tv",
    genre_ids: [10765, 18, 10759],
    popularity: 205.989,
    first_air_date: "2022-08-21",
    vote_average: 8.481,
    vote_count: 3130,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/iHSwvRVsRyxpX7FE7GbviaDvgGZ.jpg",
    id: 119051,
    name: "Wednesday",
    original_language: "en",
    original_name: "Wednesday",
    overview:
      "Wednesday Addams is sent to Nevermore Academy, a bizarre boarding school where she attempts to master her psychic powers, stop a monstrous killing spree of the town citizens, and solve the supernatural mystery that affected her family 25 years ago — all while navigating her new relationships.",
    poster_path: "/9PFonBhy4cQy7Jz20NpMygczOkv.jpg",
    media_type: "tv",
    genre_ids: [10765, 9648, 35],
    popularity: 388.186,
    first_air_date: "2022-11-23",
    vote_average: 8.597,
    vote_count: 6998,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/k6vYqk0jgrPFHwgl767MyT0fTHt.jpg",
    id: 71738,
    name: "The Orville",
    original_language: "en",
    original_name: "The Orville",
    overview:
      "Follow the crew of the not-so-functional exploratory ship in the Earth's interstellar fleet, 400 years in the future.",
    poster_path: "/78xnHh9H5wYcUeZoB0bt1UgInAW.jpg",
    media_type: "tv",
    genre_ids: [18, 35, 10765],
    popularity: 71.605,
    first_air_date: "2017-09-10",
    vote_average: 7.577,
    vote_count: 917,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/jINW7XYCw3tHDdvtHj2nmhfOzPc.jpg",
    id: 39718,
    name: "The Hour",
    original_language: "en",
    original_name: "The Hour",
    overview:
      "A behind-the-scenes drama and espionage thriller in Cold War-era England that centers on a journalist, a producer, and an anchorman for an investigative news programme.",
    poster_path: "/gxspHzwLcFMPQL3SqU3g1zqLlQL.jpg",
    media_type: "tv",
    genre_ids: [18],
    popularity: 6.178,
    first_air_date: "2011-07-19",
    vote_average: 7.508,
    vote_count: 64,
    origin_country: ["GB"],
  },
  {
    adult: false,
    backdrop_path: "/8X1BTSaUyF5rc0malaaQovpxC3f.jpg",
    id: 1418,
    name: "The Big Bang Theory",
    original_language: "en",
    original_name: "The Big Bang Theory",
    overview:
      "The sitcom is centered on five characters living in Pasadena, California: roommates Leonard Hofstadter and Sheldon Cooper; Penny, a waitress and aspiring actress who lives across the hall; and Leonard and Sheldon's equally geeky and socially awkward friends and co-workers, mechanical engineer Howard Wolowitz and astrophysicist Raj Koothrappali. The geekiness and intellect of the four guys is contrasted for comic effect with Penny's social skills and common sense.",
    poster_path: "/ooBGRQBdbGzBxAVfExiO8r7kloA.jpg",
    media_type: "tv",
    genre_ids: [35],
    popularity: 106.771,
    first_air_date: "2007-09-24",
    vote_average: 7.878,
    vote_count: 9934,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/1rO4xoCo4Z5WubK0OwdVll3DPYo.jpg",
    id: 84773,
    name: "The Lord of the Rings: The Rings of Power",
    original_language: "en",
    original_name: "The Lord of the Rings: The Rings of Power",
    overview:
      "Beginning in a time of relative peace, we follow an ensemble cast of characters as they confront the re-emergence of evil to Middle-earth. From the darkest depths of the Misty Mountains, to the majestic forests of Lindon, to the breathtaking island kingdom of Númenor, to the furthest reaches of the map, these kingdoms and characters will carve out legacies that live on long after they are gone.",
    poster_path: "/mYLOqiStMxDK3fYZFirgrMt8z5d.jpg",
    media_type: "tv",
    genre_ids: [10759, 10765, 18],
    popularity: 183.297,
    first_air_date: "2022-09-01",
    vote_average: 7.461,
    vote_count: 2017,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/ctxm191q5o3axFzQsvNPlbKoSYv.jpg",
    id: 110492,
    name: "Peacemaker",
    original_language: "en",
    original_name: "Peacemaker",
    overview:
      "The continuing story of Peacemaker – a compellingly vainglorious man who believes in peace at any cost, no matter how many people he has to kill to get it – in the aftermath of the events of “The Suicide Squad.”",
    poster_path: "/hE3LRZAY84fG19a18pzpkZERjTE.jpg",
    media_type: "tv",
    genre_ids: [10759, 10765, 18],
    popularity: 70.363,
    first_air_date: "2022-01-13",
    vote_average: 8.336,
    vote_count: 2215,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/3ILMlmC30QUnYkY3XEBOyJ82Dqu.jpg",
    id: 65930,
    name: "My Hero Academia",
    original_language: "ja",
    original_name: "僕のヒーローアカデミア",
    overview:
      "In a world where eighty percent of the population has some kind of super-powered Quirk, Izuku was unlucky enough to be born completely normal. But that won't stop him from enrolling in a prestigious hero academy. Now, he'll get his first taste of brutal rivalry from other schools as he braves the cutthroat, no-holds-barred provisional license exam.",
    poster_path: "/ivOLM47yJt90P19RH1NvJrAJz9F.jpg",
    media_type: "tv",
    genre_ids: [10759, 16],
    popularity: 41.575,
    first_air_date: "2016-04-03",
    vote_average: 8.701,
    vote_count: 4310,
    origin_country: ["JP"],
  },
];
